name: Build, Tag, and Push Docker Images

on:
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 209561932650.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push images for all environments
        run: |
          REPO=209561932650.dkr.ecr.us-east-1.amazonaws.com/actions/ayuk-repo
          for ENV in dev staging prod; do
            IMAGE_TAG=$REPO:$ENV
            echo "Building Docker image for $ENV..."
            docker build --build-arg ENV=$ENV -t $IMAGE_TAG .
            echo "Pushing Docker image $IMAGE_TAG to ECR..."
            docker push $IMAGE_TAG
          done
